version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - mergecost-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - mergecost-net

networks:
  mergecost-net:
    driver: bridge
